apiVersion: v1
kind: Service
metadata:
  name: go-app
  labels:
    app.kubernetes.io/name: go-app
spec:
  selector:
    app.kubernetes.io/name: go-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP